name: Check compilation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Docker image
      uses: epitechcontent/epitest-docker:devel
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Build
      run: make
